name: CI/CD Pipeline Test

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'
          cache: 'maven'

      # Build the project and run tests
      - name: Build with Maven
        run: mvn clean install

      # Conditional deployment simulation
      - name: Deploy if tests pass
        if: success()
        run: echo "Deployed"

      - name: Error if tests fail
        if: failure()
        run: echo "Tests failed. Deployment aborted."
